/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as Test1RouteImport } from './routes/test1'
import { Route as TestRouteImport } from './routes/test'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainFriendRequestIndexRouteImport } from './routes/(main)/friendRequest/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/signUp/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/signIn/index'
import { Route as authInitialIndexRouteImport } from './routes/(auth)/initial/index'
import { Route as mainConversationFriendUserIdRouteImport } from './routes/(main)/conversation/$friendUserId'
import { Route as mainGroupVideoGroupIdRouteImport } from './routes/(main)/group/video/$groupId'

const mainGroupGroupIdLazyRouteImport = createFileRoute(
  '/(main)/group/$groupId',
)()

const Test1Route = Test1RouteImport.update({
  id: '/test1',
  path: '/test1',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainFriendRequestIndexRoute = mainFriendRequestIndexRouteImport.update({
  id: '/friendRequest/',
  path: '/friendRequest/',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/(auth)/signUp/',
  path: '/signUp/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/(auth)/signIn/',
  path: '/signIn/',
  getParentRoute: () => rootRouteImport,
} as any)
const authInitialIndexRoute = authInitialIndexRouteImport.update({
  id: '/(auth)/initial/',
  path: '/initial/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainGroupGroupIdLazyRoute = mainGroupGroupIdLazyRouteImport
  .update({
    id: '/group/$groupId',
    path: '/group/$groupId',
    getParentRoute: () => mainRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(main)/group/$groupId.lazy').then((d) => d.Route),
  )
const mainConversationFriendUserIdRoute =
  mainConversationFriendUserIdRouteImport.update({
    id: '/conversation/$friendUserId',
    path: '/conversation/$friendUserId',
    getParentRoute: () => mainRouteRoute,
  } as any)
const mainGroupVideoGroupIdRoute = mainGroupVideoGroupIdRouteImport.update({
  id: '/group/video/$groupId',
  path: '/group/video/$groupId',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/test': typeof TestRoute
  '/test1': typeof Test1Route
  '/conversation/$friendUserId': typeof mainConversationFriendUserIdRoute
  '/group/$groupId': typeof mainGroupGroupIdLazyRoute
  '/initial': typeof authInitialIndexRoute
  '/signIn': typeof authSignInIndexRoute
  '/signUp': typeof authSignUpIndexRoute
  '/friendRequest': typeof mainFriendRequestIndexRoute
  '/group/video/$groupId': typeof mainGroupVideoGroupIdRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/test1': typeof Test1Route
  '/': typeof mainIndexRoute
  '/conversation/$friendUserId': typeof mainConversationFriendUserIdRoute
  '/group/$groupId': typeof mainGroupGroupIdLazyRoute
  '/initial': typeof authInitialIndexRoute
  '/signIn': typeof authSignInIndexRoute
  '/signUp': typeof authSignUpIndexRoute
  '/friendRequest': typeof mainFriendRequestIndexRoute
  '/group/video/$groupId': typeof mainGroupVideoGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/test': typeof TestRoute
  '/test1': typeof Test1Route
  '/(main)/': typeof mainIndexRoute
  '/(main)/conversation/$friendUserId': typeof mainConversationFriendUserIdRoute
  '/(main)/group/$groupId': typeof mainGroupGroupIdLazyRoute
  '/(auth)/initial/': typeof authInitialIndexRoute
  '/(auth)/signIn/': typeof authSignInIndexRoute
  '/(auth)/signUp/': typeof authSignUpIndexRoute
  '/(main)/friendRequest/': typeof mainFriendRequestIndexRoute
  '/(main)/group/video/$groupId': typeof mainGroupVideoGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/test1'
    | '/conversation/$friendUserId'
    | '/group/$groupId'
    | '/initial'
    | '/signIn'
    | '/signUp'
    | '/friendRequest'
    | '/group/video/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/test'
    | '/test1'
    | '/'
    | '/conversation/$friendUserId'
    | '/group/$groupId'
    | '/initial'
    | '/signIn'
    | '/signUp'
    | '/friendRequest'
    | '/group/video/$groupId'
  id:
    | '__root__'
    | '/(main)'
    | '/test'
    | '/test1'
    | '/(main)/'
    | '/(main)/conversation/$friendUserId'
    | '/(main)/group/$groupId'
    | '/(auth)/initial/'
    | '/(auth)/signIn/'
    | '/(auth)/signUp/'
    | '/(main)/friendRequest/'
    | '/(main)/group/video/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  TestRoute: typeof TestRoute
  Test1Route: typeof Test1Route
  authInitialIndexRoute: typeof authInitialIndexRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test1': {
      id: '/test1'
      path: '/test1'
      fullPath: '/test1'
      preLoaderRoute: typeof Test1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/friendRequest/': {
      id: '/(main)/friendRequest/'
      path: '/friendRequest'
      fullPath: '/friendRequest'
      preLoaderRoute: typeof mainFriendRequestIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/signUp/': {
      id: '/(auth)/signUp/'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signIn/': {
      id: '/(auth)/signIn/'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/initial/': {
      id: '/(auth)/initial/'
      path: '/initial'
      fullPath: '/initial'
      preLoaderRoute: typeof authInitialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/group/$groupId': {
      id: '/(main)/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof mainGroupGroupIdLazyRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/conversation/$friendUserId': {
      id: '/(main)/conversation/$friendUserId'
      path: '/conversation/$friendUserId'
      fullPath: '/conversation/$friendUserId'
      preLoaderRoute: typeof mainConversationFriendUserIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/group/video/$groupId': {
      id: '/(main)/group/video/$groupId'
      path: '/group/video/$groupId'
      fullPath: '/group/video/$groupId'
      preLoaderRoute: typeof mainGroupVideoGroupIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainConversationFriendUserIdRoute: typeof mainConversationFriendUserIdRoute
  mainGroupGroupIdLazyRoute: typeof mainGroupGroupIdLazyRoute
  mainFriendRequestIndexRoute: typeof mainFriendRequestIndexRoute
  mainGroupVideoGroupIdRoute: typeof mainGroupVideoGroupIdRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainConversationFriendUserIdRoute: mainConversationFriendUserIdRoute,
  mainGroupGroupIdLazyRoute: mainGroupGroupIdLazyRoute,
  mainFriendRequestIndexRoute: mainFriendRequestIndexRoute,
  mainGroupVideoGroupIdRoute: mainGroupVideoGroupIdRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  TestRoute: TestRoute,
  Test1Route: Test1Route,
  authInitialIndexRoute: authInitialIndexRoute,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
