/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/signUp/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/signIn/index'
import { Route as mainGroupGroupIdRouteImport } from './routes/(main)/group/$groupId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/(auth)/signUp/',
  path: '/signUp/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/(auth)/signIn/',
  path: '/signIn/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainGroupGroupIdRoute = mainGroupGroupIdRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/test': typeof TestRoute
  '/group/$groupId': typeof mainGroupGroupIdRoute
  '/signIn': typeof authSignInIndexRoute
  '/signUp': typeof authSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/test': typeof TestRoute
  '/': typeof mainIndexRoute
  '/group/$groupId': typeof mainGroupGroupIdRoute
  '/signIn': typeof authSignInIndexRoute
  '/signUp': typeof authSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/test': typeof TestRoute
  '/(main)/': typeof mainIndexRoute
  '/(main)/group/$groupId': typeof mainGroupGroupIdRoute
  '/(auth)/signIn/': typeof authSignInIndexRoute
  '/(auth)/signUp/': typeof authSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test' | '/group/$groupId' | '/signIn' | '/signUp'
  fileRoutesByTo: FileRoutesByTo
  to: '/test' | '/' | '/group/$groupId' | '/signIn' | '/signUp'
  id:
    | '__root__'
    | '/(main)'
    | '/test'
    | '/(main)/'
    | '/(main)/group/$groupId'
    | '/(auth)/signIn/'
    | '/(auth)/signUp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  TestRoute: typeof TestRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/signUp/': {
      id: '/(auth)/signUp/'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signIn/': {
      id: '/(auth)/signIn/'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/group/$groupId': {
      id: '/(main)/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof mainGroupGroupIdRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainGroupGroupIdRoute: typeof mainGroupGroupIdRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainGroupGroupIdRoute: mainGroupGroupIdRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  TestRoute: TestRoute,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
